evaluate:
  pamr: true
  bg_thresh: 0.4
  kp_w: 0.3

  eval_only: true
  template: custom
  task:
    - voc
    - voc20
    - context
    - context59
    - coco_stuff
    - coco_object
    - cityscapes
    - ade20k

  # training splits
  t_voc20: segmentation/configs/_base_/datasets/t_pascal_voc12_20.py
  t_context59: segmentation/configs/_base_/datasets/t_pascal_context59.py

  # evaluation
  voc: segmentation/configs/_base_/datasets/pascal_voc12.py
  voc20: segmentation/configs/_base_/datasets/pascal_voc12_20.py
  context: segmentation/configs/_base_/datasets/pascal_context.py
  context59: segmentation/configs/_base_/datasets/pascal_context59.py
  coco_stuff: segmentation/configs/_base_/datasets/stuff.py
  coco_object: segmentation/configs/_base_/datasets/coco.py
  cityscapes: segmentation/configs/_base_/datasets/cityscapes.py
  ade20k: segmentation/configs/_base_/datasets/ade20k.py
